# Generated by Django 3.2.11 on 2022-01-30 16:22

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_homepage_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='body',
            field=wagtail.core.fields.StreamField([('banner', wagtail.core.blocks.StructBlock([('banner', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('banner_title', wagtail.core.blocks.CharBlock(help_text='Banner title. Max length of 50 characters.', max_length=50)), ('banner_lead_text', wagtail.core.blocks.TextBlock(help_text='Lead text. Max length is 50 characters.', max_length=50, required=False)), ('banner_image', wagtail.images.blocks.ImageChooserBlock(help_text='Banner background image.'))])))])), ('about', wagtail.core.blocks.StructBlock([('about', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('about_title', wagtail.core.blocks.CharBlock(help_text='About section title. Max length of 50 characters.', max_length=50)), ('about_lead_text', wagtail.core.blocks.CharBlock(help_text='Lead text. Max length is 50 characters.', max_length=50, required=False)), ('about_image', wagtail.images.blocks.ImageChooserBlock(help_text='About profile image.')), ('first_paragrapher', wagtail.core.blocks.TextBlock(help_text='First paragrapher. Max length is 500 characters.', max_length=50, required=False)), ('second_paragrapher', wagtail.core.blocks.TextBlock(help_text='Second paragrapher. Max length is 500 characters.', max_length=50, required=False))])))])), ('projects', wagtail.core.blocks.StructBlock([('projects', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('projects_title', wagtail.core.blocks.CharBlock(help_text='Projects section title. Max length of 50 characters.', max_length=50)), ('projects_lead_text', wagtail.core.blocks.TextBlock(help_text='Lead text. Max length is 50 characters.', max_length=50, required=False))])))]))], blank=True, null=True),
        ),
    ]
