# Generated by Django 4.0 on 2022-02-12 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0023_add_choose_permissions'),
        ('home', '0007_alter_homepage_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_first_paragrapher',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_image',
            field=models.ForeignKey(help_text='Vertical profile image 3x2 aspect ratio', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_lead_text',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_second_paragrapher',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_title',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_lead_text',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_title',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_lead_text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='portfolio_title',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
