# Generated by Django 4.0 on 2022-02-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_remove_homepage_body_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='hero_mask',
            field=models.CharField(help_text="Enter number from '0' to 1000' for change mask", max_length=4, null=True),
        ),
    ]
