# Generated by Django 4.0 on 2022-02-12 15:31

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_homepage_hero_mask'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='about_first_paragrapher',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='about_second_paragrapher',
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_lead_text',
            field=wagtail.core.fields.RichTextField(null=True),
        ),
    ]
