# Generated by Django 4.0 on 2022-02-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_remove_homepage_about_first_paragrapher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='about_first_paragrapher',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='about_second_paragrapher',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='about_lead_text',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
