# Generated by Django 4.0 on 2022-02-12 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_homepage_about_first_paragrapher_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='contact_email',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_email_title',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_instagram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_lead_text',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_phone',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_phone_title',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_section_title',
            field=models.CharField(max_length=140, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_telegram',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_tiktok',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_vk',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='contact_whatsapp',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='social_network_title',
            field=models.CharField(max_length=140, null=True),
        ),
    ]
