# Generated by Django 4.0 on 2022-02-12 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_homepage_contact_email_homepage_contact_email_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='contact_email',
            field=models.TextField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='contact_phone',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
