# Generated by Django 4.0 on 2022-02-12 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_alter_homepage_contact_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homepage',
            name='contact_lead_text',
            field=models.TextField(max_length=500, null=True),
        ),
    ]
