# Generated by Django 3.2.11 on 2022-01-31 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0066_collection_management_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vk', models.URLField(blank=True, help_text='Enter your Vk URL')),
                ('facebook', models.URLField(blank=True, help_text='Enter your Facebook URL')),
                ('instagram', models.URLField(blank=True, help_text='Enter your Instagram URL')),
                ('twitter', models.URLField(blank=True, help_text='Enter your Twitter URL')),
                ('tiktok', models.URLField(blank=True, help_text='Enter your TikTok URL')),
                ('github', models.URLField(blank=True, help_text='Enter your GitHub URL')),
                ('linkedin', models.URLField(blank=True, help_text='Enter your LinkedIn URL')),
                ('youtube', models.URLField(blank=True, help_text='Enter your Youtube URL')),
                ('whatsapp', models.URLField(blank=True, help_text='Enter your Whatsapp URL')),
                ('telegram', models.URLField(blank=True, help_text='Enter your Telegram URL')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NavbarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(blank=True, help_text='Enter your Brand, it will appear on the navbar', max_length=50, null=True)),
                ('about', models.CharField(blank=True, help_text='Choose how to call the link for "About" section in navabar', max_length=50, null=True)),
                ('portfolio', models.CharField(blank=True, help_text='Choose how to call the link for "Portfolio" page in navabar', max_length=50, null=True)),
                ('contact', models.CharField(blank=True, help_text='Choose how to call the link for "Contact" section in navabar', max_length=50, null=True)),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
