# Generated by Django 3.2.11 on 2022-01-31 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbarsettings',
            name='about',
            field=models.CharField(help_text='Choose how to call the link for "About" section in navabar', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='navbarsettings',
            name='brand',
            field=models.CharField(help_text='Enter your Brand, it will appear on the navbar', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='navbarsettings',
            name='contact',
            field=models.CharField(help_text='Choose how to call the link for "Contact" section in navabar', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='navbarsettings',
            name='portfolio',
            field=models.CharField(help_text='Choose how to call the link for "Portfolio" page in navabar', max_length=50, null=True),
        ),
    ]
