# Generated by Django 4.0 on 2022-02-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0003_footersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarsettings',
            name='home',
            field=models.CharField(help_text='Choose how to call the link for "Home" section in navabar', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='navbarsettings',
            name='portfolio',
            field=models.CharField(help_text='Choose how to call the link for "Work" section in navabar', max_length=50, null=True),
        ),
    ]
